# Generated by Django 4.2.5 on 2025-04-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_content_message_message_alter_message_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='encrypted_message',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
